name: check golangci-lint config
on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  check:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golangci-lint-version: ["v1", "v2"]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Check out code into the Go module directory
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set TAG_NAME
        if: ${{ matrix.golangci-lint-version == 'v1' }}
        run: echo "TAG_NAME=v1.64.8" >> "$GITHUB_ENV"
      - name: Set TAG_NAME
        if: ${{ matrix.golangci-lint-version != 'v1' }}
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: echo "TAG_NAME=$(gh release list --repo golangci/golangci-lint --json name,isLatest --jq '.[] | select(.isLatest) | .name')" >> "$GITHUB_ENV"
      - name: Install golangci-lint
        run: |
          curl -sSfL "https://raw.githubusercontent.com/golangci/golangci-lint/refs/tags/$TAG_NAME/install.sh" | sh -s -- -b "$(go env GOPATH)/bin" "$TAG_NAME"
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Validate golangci-lint config
        run: golangci-lint config verify --config=.github/.golangci.${{ matrix.golangci-lint-version }}.yml
